POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RuYW1lIiwiaWQiOiI2MGZjNzc1MmQ1NmQ5YzQ0MzRiNGVkMTIiLCJpYXQiOjE2MjcxNjIxMTh9.cksYzoaGtVJ9l_r0YkVjkqPthWQR0aF8uFb-NBBNfDI

{
  "content": "TESTING auth header",
  "important": true
}