DELETE http://localhost:3001/api/notes/6105639597e2962e08c3cbf8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RuYW1lIiwiaWQiOiI2MTA1NjIzNGZjMTU3OTUxMDQwZmRjYjIiLCJpYXQiOjE2Mjc3NDI3NzgsImV4cCI6MTYyNzc0NjM3OH0.Xlp6P3lIIQDDOiomUf2Ht0UvhT54cZV-enmuUh3Czgg
